### ISSUE TITLE
Failing to install in Github Actions

### ISSUE THREAD

**Issue by FluidSense** [avh4/elm-format#821]
Hello 👋 

I am trying to add `elm-format` as a dependency to a project, but the step `npm ci` of my Github Action fails on a relatively simple setup.

```term
npm ERR! -- ERROR -----------------------------------------------------------------------
npm ERR! 
npm ERR! I support your platform, but I could not find the binary package (@avh4/elm-format-linux-x64) for it!
npm ERR! 
npm ERR! This can happen if you use the "--omit=optional" (or "--no-optional") npm flag.
npm ERR! The "optionalDependencies" package.json feature is used by elm-format to install the correct
npm ERR! binary executable for your current platform. Remove that flag to use elm-format.
npm ERR! 
npm ERR! This can also happen if the "node_modules" folder was copied between two operating systems
npm ERR! that need different binaries - including "virtual" operating systems like Docker and WSL.
npm ERR! If so, try installing with npm rather than copying "node_modules".
npm ERR! 
npm ERR! NOTE: You can avoid npm entirely by downloading directly from:
npm ERR! https://github.com/avh4/elm-format/releases/tag/0.8.7
npm ERR! All this package does is distributing a file from there.
npm ERR! 
npm ERR! --------------------------------------------------------------------------------
```

The workflow file is as little as this:

```yaml
name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm test
    ```
    
Have I missed something obvious? I tried searching through previous issues, but I could not find anyone with a similar problem.

Any help appreciated!
